# Generated by Django 6.0 on 2026-01-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarz'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='expensemachine',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Summasi'),
        ),
        migrations.AlterField(
            model_name='expensemachine',
            name='expense_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Harajat sanasi'),
        ),
        migrations.AlterField(
            model_name='expensemachine',
            name='expense_type',
            field=models.CharField(choices=[('Usta Haqqi', 'Usta Haqqi'), ('Kran', 'Kran'), ('Qolip Sotib Olish', 'Qolip Sotib Olish')], max_length=50, verbose_name='Harajat turi'),
        ),
        migrations.AlterField(
            model_name='expensemachine',
            name='info',
            field=models.TextField(max_length=255, verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Summasi'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Harajat sanasi'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('Oylik', 'Oylik'), ('Oziq-ovqat', 'Oziq-ovqat'), ('Soliq', 'Soliq'), ('Elektr', 'Elektr'), ('Internet', 'Internet')], max_length=20, verbose_name='Harajat turi'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='worker_name',
            field=models.CharField(max_length=100, verbose_name='Xodim ismi'),
        ),
        migrations.AlterField(
            model_name='investors',
            name='age',
            field=models.IntegerField(verbose_name='Yosh'),
        ),
        migrations.AlterField(
            model_name='investors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='investors',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='investors',
            name='invest',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Sarmoya miqdori'),
        ),
        migrations.AlterField(
            model_name='investors',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='investors',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan sana'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.suppliers', verbose_name='Yetkazib beruvchi'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot"),
        ),
        migrations.AlterField(
            model_name='sales',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='Qarzdorlik'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.products', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan sana'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarz'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam'),
        ),
    ]
