# Generated by Django 6.0 on 2026-01-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customers_debt_alter_customers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemachine',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='worker_name',
            field=models.CharField(default='-', max_length=100, verbose_name='Xodim ismi'),
        ),
    ]
