# Generated by Django 6.0 on 2026-01-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_expensemachine_info_alter_expenses_worker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot"),
        ),
    ]
