# Generated by Django 6.0 on 2026-01-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customers_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot"),
        ),
        migrations.CreateModel(
            name='PaymentDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Qarz undirish', 'Qarz undirish'), ("Qarzni to'lash", "Qarzni to'lash")], max_length=50, verbose_name="To'lov turi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name="To'langan summa")),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customers', verbose_name='Xaridor')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.suppliers', verbose_name='Yetkazib beruvchi')),
            ],
        ),
    ]
