# Generated by Django 6.0 on 2026-01-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_suppliers_info_paymentdebt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarz miqdori')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='SExpenseMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mashina nomi')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Harajat miqdori')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('expense_date', models.DateTimeField(auto_now_add=True, verbose_name='Harajat sanasi')),
            ],
        ),
        migrations.CreateModel(
            name='SExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(choices=[('Ishchi oyligi', 'Ishchi oyligi'), ('Elektr energiyasi', 'Elektr energiyasi'), ("Suv to'lovi", "Suv to'lovi"), ('soliq', 'Soliq'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Harajat turi')),
                ('worker', models.CharField(default='-', max_length=100, verbose_name='Xodim ismi')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Harajat miqdori')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('expense_date', models.DateTimeField(auto_now_add=True, verbose_name='Harajat sanasi')),
            ],
        ),
        migrations.CreateModel(
            name='SProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Narxi')),
            ],
        ),
        migrations.CreateModel(
            name='SSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarz')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='SSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Narxi')),
                ('is_debt', models.BooleanField(default=False, verbose_name='Qarzdorlik')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan sana')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scustomers', verbose_name='Xaridor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_sales', to='api.sproducts', verbose_name='Mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='SPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Narxi')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sproducts', verbose_name='Mahsulot nomi')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ssupplier', verbose_name='Yetkazib beruvchi')),
            ],
        ),
        migrations.CreateModel(
            name='SPaymentDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Qarz undirish', 'Qarz undirish'), ("Qarzni to'lash", "Qarzni to'lash")], max_length=50, verbose_name="To'lov turi")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name="To'langan summa")),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.scustomers', verbose_name='Xaridor')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ssupplier', verbose_name='Yetkazib beruvchi')),
            ],
        ),
    ]
