# Generated by Django 6.0 on 2026-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scustomers_sexpensemachine_sexpenses_sproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('Oylik', 'Oylik'), ('Oziq-ovqat', 'Oziq-ovqat'), ('Soliq', 'Soliq'), ('Arenda ', 'Arenda'), ('Elektr', 'Elektr'), ('Internet', 'Internet')], max_length=20, verbose_name='Harajat turi'),
        ),
        migrations.AlterField(
            model_name='sexpenses',
            name='expense',
            field=models.CharField(choices=[('Ishchi oyligi', 'Ishchi oyligi'), ('Elektr energiyasi', 'Elektr energiyasi'), ('Arenda', 'Arenda'), ("Suv to'lovi", "Suv to'lovi"), ('soliq', 'Soliq'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Harajat turi'),
        ),
    ]
