# Generated by Django 6.0 on 2026-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_expenses_expense_type_alter_sexpenses_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='Qarzdorlik'),
        ),
        migrations.AddField(
            model_name='spurchases',
            name='is_debt',
            field=models.BooleanField(default=False, verbose_name='Qarzdorlik'),
        ),
    ]
