# Generated by Django 6.0 on 2026-01-10 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_purchases_is_debt_spurchases_is_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarz')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='SalExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ishchi oyligi', 'Ishchi oyligi'), ("Texnika ta'mirlash", "Texnika ta'mirlash"), ('Oziq-ovqat', 'Oziq-ovqat'), ('Elektr energiyasi', 'Elektr energiyasi'), ('Soliq', 'Soliq'), ('internet', 'Internet'), ('Arenda', 'Arenda')], max_length=100, verbose_name='Xarajat turi')),
                ('worker', models.CharField(default="Noma'lum", max_length=100, verbose_name='Xodim ismi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Xarajat miqdori')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('expense_date', models.DateTimeField(auto_now_add=True, verbose_name='Xarajat sanasi')),
            ],
        ),
        migrations.CreateModel(
            name='SalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Narxi')),
            ],
        ),
        migrations.CreateModel(
            name='SalSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Telefon raqam')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarz')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
        ),
        migrations.CreateModel(
            name='SalSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Narxi')),
                ('is_debt', models.BooleanField(default=False, verbose_name='Qarzdorlik')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan sana')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salcustomers', verbose_name='Mijoz')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salproducts', verbose_name='Mahsulot nomi')),
            ],
        ),
        migrations.CreateModel(
            name='SalPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Narxi')),
                ('is_debt', models.BooleanField(default=False, verbose_name='Qarzdorlik')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan sana')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salsuppliers', verbose_name='Yetkazib beruvchi')),
            ],
        ),
        migrations.CreateModel(
            name='SalPaymentDebts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Qarz undirish', 'Qarz undirish'), ("Qarz to'lash", "Qarz to'lash")], max_length=50, verbose_name="To'lov turi")),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=25, verbose_name="To'langan summa")),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name="To'lov sanasi")),
                ('info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salcustomers', verbose_name='Mijoz')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salsuppliers', verbose_name='Yetkazib beruvchi')),
            ],
        ),
    ]
