# Generated by Django 6.0 on 2026-01-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_salcustomers_salexpenses_salproducts_salsuppliers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentabr', 'Sentabr'), ('Oktabr', 'Oktabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], max_length=20, verbose_name='Hisobot')),
                ('from_date', models.DateTimeField(verbose_name='Boshlanish sanasi')),
                ('to_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami xaridlar')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami sotuvlar')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami xarajatlar')),
                ('total_expense_machine', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami stanog xarajatlari')),
                ('total_supplier_debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarzlarimiz')),
                ('total_customer_debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Haqlarimiz')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Sof foyda')),
            ],
        ),
        migrations.CreateModel(
            name='SalMonthlyReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentabr', 'Sentabr'), ('Oktabr', 'Oktabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], max_length=20, verbose_name='Hisobot')),
                ('from_date', models.DateTimeField(verbose_name='Boshlanish sanasi')),
                ('to_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami xaridlar')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami sotuvlar')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami xarajatlar')),
                ('total_customer_debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Haqlarimiz')),
                ('total_supplier_debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarzlarimiz')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Sof foyda')),
            ],
        ),
        migrations.CreateModel(
            name='SMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Yanvar', 'Yanvar'), ('Fevral', 'Fevral'), ('Mart', 'Mart'), ('Aprel', 'Aprel'), ('May', 'May'), ('Iyun', 'Iyun'), ('Iyul', 'Iyul'), ('Avgust', 'Avgust'), ('Sentabr', 'Sentabr'), ('Oktabr', 'Oktabr'), ('Noyabr', 'Noyabr'), ('Dekabr', 'Dekabr')], max_length=20, verbose_name='Hisobot')),
                ('from_date', models.DateTimeField(verbose_name='Boshlanish sanasi')),
                ('to_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami xaridlar')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami sotuvlar')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami xarajatlar')),
                ('total_expense_machine', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Jami stanog xarajatlari')),
                ('total_customer_debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Haqlarimiz')),
                ('total_supplier_debt', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Qarzlarimiz')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='Sof foyda')),
            ],
        ),
    ]
