# Generated by Django 6.0 on 2026-01-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_monthlyreport_salmonthlyreports_smonthlyreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Xaridor', 'verbose_name_plural': 'Xaridorlar'},
        ),
        migrations.AlterModelOptions(
            name='expensemachine',
            options={'verbose_name': 'Stanoq Harajati', 'verbose_name_plural': 'Stanoq Harajatlari'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Harajat', 'verbose_name_plural': 'Harajatlar'},
        ),
        migrations.AlterModelOptions(
            name='investors',
            options={'verbose_name': 'Investor', 'verbose_name_plural': 'Investorlar'},
        ),
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'verbose_name': 'Oylik Hisobot', 'verbose_name_plural': 'Oylik Hisobotlar'},
        ),
        migrations.AlterModelOptions(
            name='paymentdebt',
            options={'verbose_name': "Qarz To'lovi", 'verbose_name_plural': "Qarz To'lovlari"},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Xarid', 'verbose_name_plural': 'Xaridlar'},
        ),
        migrations.AlterModelOptions(
            name='salcustomers',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.AlterModelOptions(
            name='salexpenses',
            options={'verbose_name': 'Xarajat', 'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.AlterModelOptions(
            name='salmonthlyreports',
            options={'verbose_name': 'Oylik Hisobot', 'verbose_name_plural': 'Oylik Hisobotlar'},
        ),
        migrations.AlterModelOptions(
            name='salpaymentdebts',
            options={'verbose_name': "Qarz To'lovi", 'verbose_name_plural': "Qarz To'lovlari"},
        ),
        migrations.AlterModelOptions(
            name='salproducts',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='salpurchases',
            options={'verbose_name': 'Xarid', 'verbose_name_plural': 'Xaridlar'},
        ),
        migrations.AlterModelOptions(
            name='salsales',
            options={'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.AlterModelOptions(
            name='salsuppliers',
            options={'verbose_name': 'Yetkazib beruvchi', 'verbose_name_plural': 'Yetkazib beruvchilar'},
        ),
        migrations.AlterModelOptions(
            name='scustomers',
            options={'verbose_name': 'Xaridor', 'verbose_name_plural': 'Xaridorlar'},
        ),
        migrations.AlterModelOptions(
            name='sexpensemachine',
            options={'verbose_name': 'Stanog Xarajati', 'verbose_name_plural': 'Stanog Xarajatlari'},
        ),
        migrations.AlterModelOptions(
            name='sexpenses',
            options={'verbose_name': 'Xarajat', 'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.AlterModelOptions(
            name='smonthlyreport',
            options={'verbose_name': 'Oylik Hisobot', 'verbose_name_plural': 'Oylik Hisobotlar'},
        ),
        migrations.AlterModelOptions(
            name='spaymentdebt',
            options={'verbose_name': "Qarz To'lovi", 'verbose_name_plural': "Qarz To'lovlari"},
        ),
        migrations.AlterModelOptions(
            name='sproducts',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='spurchases',
            options={'verbose_name': 'Xarid', 'verbose_name_plural': 'Xaridlar'},
        ),
        migrations.AlterModelOptions(
            name='ssales',
            options={'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.AlterModelOptions(
            name='ssupplier',
            options={'verbose_name': 'Yetkazib beruvchi', 'verbose_name_plural': 'Yetkazib beruvchilar'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'Yetkazib beruvchi', 'verbose_name_plural': 'Yetkazib beruvchilar'},
        ),
    ]
