"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['*']

from dotenv import load_dotenv
load_dotenv()

import os
DEBUG = os.getenv("DEBUG") == "True"

# Application definition

INSTALLED_APPS = [
    "unfold",  
    "unfold.contrib.filters", 
    "unfold.contrib.forms",  
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",  
    "unfold.contrib.guardian",  
    "unfold.contrib.simple_history",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()  # .env faylni yuklaydi

SECRET_KEY = os.getenv("SECRET_KEY")
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}


from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "SAFO | Ishlab chiqarish korxonasi",
    "SITE_HEADER": "SAFO",
    "SITE_SUBHEADER": "Ishlab chiqarish korxonasi boshqaruvi",
    "SITE_URL": "/",

    "SHOW_HISTORY": True, 
    "SHOW_VIEW_ON_SITE": True, 
    "SHOW_BACK_BUTTON": True,

    "BORDER_RADIUS": "10px",


    # Styles
    "STYLES": [
        lambda request: static("css/styles.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/scripts.js"),
    ],

    "SIDEBAR": {
        "show_search": True,  
        "show_all_applications": True, 
        "navigation": [
            {
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                   
                ],
            },
            {
                "title": _("Adminlar boshqaruvi"),
                "separator": False,
                "collapsible": True, 
                "items": [
                    {
                        "title": _("Adminlar"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_user"),
                    },
                    {
                        "title": _("Admin ruxsatlari"),
                        "icon": "folder_supervised",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                ],
            },
            {
                "title": _("Korzinka sehi"),
                "separator": False,
                "collapsible": True, 
                "items": [
                    {
                        "title": _("Sarmoyadorlar"),
                        "icon": "monetization_on",
                        "link": reverse_lazy("admin:api_investors_changelist"),
                        "permission": lambda request: request.user.has_perm("api.investors_view"),
                    },
                    {
                        "title": _("Mahsulot qabul qilish"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_purchases_changelist"),
                        "permission": lambda request: request.user.has_perm("api.purchases_view"),
                    },
                    {
                        "title": _("Sotuvlar"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:api_sales_changelist"),
                        "permission": lambda request: request.user.has_perm("api.sales_view"),
                    },
                    {
                        "title": _("Mahsulotlar ombori"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_products_changelist"),
                        "permission": lambda request: request.user.has_perm("api.products_view"),
                    },
                    {
                        "title": _("Haridorlar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_customers_changelist"),
                        "permission": lambda request: request.user.has_perm("api.customers_view"),
                    },
                    {
                        "title": _("Yetkazib beruvchilar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_suppliers_changelist"),
                        "permission": lambda request: request.user.has_perm("api.suppliers_view"),
                    },
                    {
                        "title": _("Qarzdorlik to'lovlari"),
                        "icon": "payment",
                        "link": reverse_lazy("admin:api_paymentdebt_changelist"),
                        "permission": lambda request: request.user.has_perm("api.paymentdebt_view"),
                    },
                    {
                        "title": _("Harajatlar "),
                        "icon": " list",
                        "link": reverse_lazy("admin:api_expenses_changelist"),
                        "permission": lambda request: request.user.has_perm("api.expenses_view"),
                    },
                    {
                        "title": _("Stanog harajatlari "),
                        "icon": " list",
                        "link": reverse_lazy("admin:api_expensemachine_changelist"),
                        "permission": lambda request: request.user.has_perm("api.expensemachine_view"),
                    },
                    {
                        "title": _("Oylik hisobotlar"),
                        "icon": "assessment",
                        "link": reverse_lazy("admin:api_monthlyreport_changelist"),
                        "permission": lambda request: request.user.has_perm("api.monthlyreport_view"),
                    },
                ],
                
            },
            {
                "title": _("Seriyo sehi"),
                "separator": False,
                "icon": "settings",
                "collapsible": True,
                "items": [
                    {
                        "title": _("Mahsulot qabul qilish"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_spurchases_changelist"),
                        "permission": lambda request: request.user.has_perm("api.spurchases_view"),
                    },
                    {
                        "title": _("Sotuvlar"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:api_ssales_changelist"),
                        "permission": lambda request: request.user.has_perm("api.ssales_view"),
                    },
                    {
                        "title": _("Mahsulotlar ombori"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_sproducts_changelist"),
                        "permission": lambda request: request.user.has_perm("api.sproducts_view"),
                    },
                    {
                        "title": _("Haridorlar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_scustomers_changelist"),
                        "permission": lambda request: request.user.has_perm("api.scustomers_view"),
                    },
                    {
                        "title": _("Yetkazib beruvchilar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_ssupplier_changelist"),
                        "permission": lambda request: request.user.has_perm("api.ssupplier_view"),
                    },
                    {
                        "title": _("Qarzdorlik to'lovlari"),
                        "icon": "payment",
                        "link": reverse_lazy("admin:api_spaymentdebt_changelist"),
                        "permission": lambda request: request.user.has_perm("api.spaymentdebt_view"),
                    },
                    {
                        "title": _("Harajatlar "),
                        "icon": " list",
                        "link": reverse_lazy("admin:api_sexpenses_changelist"),
                        "permission": lambda request: request.user.has_perm("api.sexpenses_view"),
                    },
                    {
                        "title": _("Stanog harajatlari "),
                        "icon": " list",
                        "link": reverse_lazy("admin:api_sexpensemachine_changelist"),
                        "permission": lambda request: request.user.has_perm("api.sexpensemachine_view"),
                    },
                    {
                        "title": _("Oylik hisobotlar"),
                        "icon": "assessment",
                        "link": reverse_lazy("admin:api_smonthlyreport_changelist"),
                        "permission": lambda request: request.user.has_perm("api.smonthlyreport_view"),
                    },
                ],
            },
            {
                "title": _("Salfetka sehi"),
                "separator": False,
                "collapsible": True, 
                "items": [
                    {
                        "title": _("Mahsulot qabul qilish"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_salpurchases_changelist"),
                        "permission": lambda request: request.user.has_perm("api.salpurchases_view"),
                    },
                    {
                        "title": _("Sotuvlar"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:api_salsales_changelist"),
                        "permission": lambda request: request.user.has_perm("api.salsales_view"),
                    },
                    {
                        "title": _("Mahsulotlar ombori"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_salproducts_changelist"),
                        "permission": lambda request: request.user.has_perm("api.salproducts_view"),
                    },
                    {
                        "title": _("Haridorlar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_salcustomers_changelist"),
                        "permission": lambda request: request.user.has_perm("api.salcustomers_view"),
                    },
                    {
                        "title": _("Yetkazib beruvchilar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_salsuppliers_changelist"),
                        "permission": lambda request: request.user.has_perm("api.salsuppliers_view"),
                    },
                    {
                        "title": _("Qarzdorlik to'lovlari"),
                        "icon": "payment",
                        "link": reverse_lazy("admin:api_salpaymentdebts_changelist"),
                        "permission": lambda request: request.user.has_perm("api.salpaymentdebts_view"),
                    },
                    {
                        "title": _("Harajatlar "),
                        "icon": " list",
                        "link": reverse_lazy("admin:api_salexpenses_changelist"),
                        "permission": lambda request: request.user.has_perm("api.salexpenses_view"),
                    },
                    {
                        "title": _("Oylik hisobotlar"),
                        "icon": "assessment",
                        "link": reverse_lazy("admin:api_salmonthlyreports_changelist"),
                        "permission": lambda request: request.user.has_perm("api.salmonthlyreports_view"),
                    },
                ],
            },
            ],
    },
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
