"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t3n_tj=e9+!te4g-^a!)yfcd$1y-5qz=^6eyj4f(5p!)9%6($f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "unfold",  
    "unfold.contrib.filters", 
    "unfold.contrib.forms",  
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",  
    "unfold.contrib.guardian",  
    "unfold.contrib.simple_history",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Administration",
    "SITE_HEADER": "Safo Korzinka",
    "SITE_SUBHEADER": "Buhgalteiya boshqaruvi",
    "SITE_URL": "/",

    "SHOW_HISTORY": True, 
    "SHOW_VIEW_ON_SITE": True, 
    "SHOW_BACK_BUTTON": True,

    "BORDER_RADIUS": "10px",


    # Styles
    "STYLES": [
        lambda request: static("css/styles.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/scripts.js"),
    ],

    "SIDEBAR": {
        "show_search": True,  
        "show_all_applications": True, 
        "navigation": [
            {
                "separator": True,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                   
                ],
            },
            {
                "title": _("Adminlar boshqaruvi"),
                "separator": False,
                "collapsible": True, 
                "items": [
                    {
                        "title": _("Adminlar"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_user"),
                    },
                    {
                        "title": _("Admin ruxsatlari"),
                        "icon": "folder_supervised",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.has_perm("auth.view_group"),
                    },
                ],
            },
            {
                "title": _("Korzinka sehi"),
                "separator": False,
                "collapsible": False, 
                "items": [
                    {
                        "title": _("Sarmoyadorlar"),
                        "icon": "monetization_on",
                        "link": reverse_lazy("admin:api_investors_changelist"),
                        "permission": lambda request: request.user.has_perm("api.investors_view"),
                    },
                    {
                        "title": _("Mahsulot qabul qilish"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_purchases_changelist"),
                        "permission": lambda request: request.user.has_perm("api.purchases_view"),
                    },
                    {
                        "title": _("Sotuvlar"),
                        "icon": "point_of_sale",
                        "link": reverse_lazy("admin:api_sales_changelist"),
                        "permission": lambda request: request.user.has_perm("api.sales_view"),
                    },
                    {
                        "title": _("Mahsulotlar ombori"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:api_products_changelist"),
                        "permission": lambda request: request.user.has_perm("api.products_view"),
                    },
                    {
                        "title": _("Mijozlar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_customers_changelist"),
                        "permission": lambda request: request.user.has_perm("api.customers_view"),
                    },
                    {
                        "title": _("Yetkazib beruvchilar"),
                        "icon": "people_alt",
                        "link": reverse_lazy("admin:api_suppliers_changelist"),
                        "permission": lambda request: request.user.has_perm("api.suppliers_view"),
                    },
                    {
                        "title": _("Harajatlar "),
                        "icon": " list",
                        "link": reverse_lazy("admin:api_expenses_changelist"),
                        "permission": lambda request: request.user.has_perm("api.expenses_view"),
                    },
                    {
                        "title": _("Stanog harajatlari "),
                        "icon": " list",
                        "link": reverse_lazy("admin:api_expensemachine_changelist"),
                        "permission": lambda request: request.user.has_perm("api.expensemachine_view"),
                    },
                ],
                
            },
            ],
    },
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
